apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
  namespace: elasticsearch
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
  serviceName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
    spec:
      terminationGracePeriodSeconds: 300
      initContainers:
        # NOTE:
        # This is to fix the permission on the volume
        # By default elasticsearch container is not run as non root user.
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
        - name: fix-the-volume-permission
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/data
          securityContext:
            privileged: true
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
        # NOTE:
        # To increase the ulimit
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
        - name: increase-the-ulimit
          image: busybox
          command:
            - sh
            - -c
            - ulimit -n 262144
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: iteam1337/elasticsearch:7.17.10
          imagePullPolicy: Always
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /data
          resources:
            requests:
              cpu: "0.5"
              memory: "2G"
          env:
            - name: path.data
              value: /data/elasticsearch
            - name: cluster.name
              value: elasticsearch
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: -Xms2g -Xmx2g
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "50Gi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
  namespace: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
    - port: 9300
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    app.kubernetes.io/name: elasticsearch
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kibana
  namespace: elasticsearch
spec:
  interval: 24h
  url: https://helm.elastic.co
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: kibana
#   namespace: elasticsearch
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: kibana
#       version: "7"
#       sourceRef:
#         kind: HelmRepository
#         name: kibana
#         namespace: elasticsearch
#       interval: 12h
#   values:
#     elasticsearchHosts: http://elasticsearch:9200
#     nodeSelector:
#       role: worker
#     resources:
#       requests:
#         cpu: "100m"
#         memory: "512M"
#       limits:
#         cpu: "1"
#         memory: "1Gi"
