---
apiVersion: v1
kind: Namespace
metadata:
  name: rancher
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rancher
  namespace: rancher
spec:
  interval: 24h
  url: https://releases.rancher.com/server-charts/latest
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: rancher
spec:
  interval: 30m
  chart:
    spec:
      chart: rancher
      version: "2.7.x"
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: rancher
      interval: 12h
  values:
    hostname: cloud.iteam.services
    ingress.tls.source: letsEncrypt
    letsEncrypt.email: registry@iteam.se
